name: tests

on:
  push:
    branches: [ main ]
  pull_request:
      branches: [ main ] 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Run tests
        run: |
          pip install -e .
          pip install -r tests/devops_tests/requirements.txt
          pytest -vv -rP -We tests/devops_tests/test_notebooks.py::test_run_notebooks
